function FABridge(a,c){this.target=a;this.remoteTypeCache={};this.remoteInstanceCache={};this.remoteFunctionCache={};this.localFunctionCache={};this.bridgeID=FABridge.nextBridgeID++;this.name=c;this.nextLocalFuncID=0;FABridge.instances[this.name]=this;FABridge.idMap[this.bridgeID]=this;return this}FABridge.TYPE_ASINSTANCE=1;FABridge.TYPE_ASFUNCTION=2;FABridge.TYPE_JSFUNCTION=3;FABridge.TYPE_ANONYMOUS=4;FABridge.initCallbacks={};FABridge.userTypes={};
FABridge.addToUserTypes=function(){for(var a=0;a<arguments.length;a++)FABridge.userTypes[arguments[a]]={typeName:arguments[a],enriched:!1}};FABridge.argsToArray=function(a){for(var c=[],b=0;b<a.length;b++)c[b]=a[b];return c};FABridge.isArray=function(a){return!!a&&(a instanceof Array||"[object Array]"===Object.prototype.toString.call(a))};FABridge.isASProxy=function(a){return!!a&&(a instanceof ASProxy||!!a.bridgeName&&!!a.typeName&&"ASProxy"===a.className)};
function instanceFactory(a){this.fb_instance_id=a;return this}function FABridge__invokeJSFunction(a){var c=a[0];a=a.concat();a.shift();return FABridge.extractBridgeFromID(c).invokeLocalFunction(c,a)}FABridge.addInitializationCallback=function(a,c){var b=FABridge.instances[a];void 0!=b?c.call(b):(b=FABridge.initCallbacks[a],null==b&&(FABridge.initCallbacks[a]=b=[]),b.push(c))};
function FABridge__bridgeInitialized(a){var c=document.getElementsByTagName("object"),b=c.length,e=[];if(0<b)for(var d=0;d<b;d++)"undefined"!=typeof c[d].SetVariable&&(e[e.length]=c[d]);b=document.getElementsByTagName("embed");d=b.length;c=[];if(0<d)for(var h=0;h<d;h++)"undefined"!=typeof b[h].SetVariable&&(c[c.length]=b[h]);h=e.length;b=c.length;d="bridgeName="+a;if(1==h&&!b||1==h&&1==b)FABridge.attachBridge(e[0],a);else if(1==b&&!h)FABridge.attachBridge(c[0],a);else{var r=!1;if(1<h)for(var v=0;v<
h;v++){for(var D=e[v].childNodes,s=0;s<D.length;s++){var B=D[s];if(1==B.nodeType&&"param"==B.tagName.toLowerCase()&&"flashvars"==B.name.toLowerCase()&&0<=B.value.indexOf(d)){FABridge.attachBridge(e[v],a);r=!0;break}}if(r)break}if(!r&&1<b)for(e=0;e<b;e++)if(0<=c[e].attributes.getNamedItem("flashVars").nodeValue.indexOf(d)){FABridge.attachBridge(c[e],a);break}}return!0}FABridge.nextBridgeID=0;FABridge.instances={};FABridge.idMap={};FABridge.refCount=0;
FABridge.extractBridgeFromID=function(a){return FABridge.idMap[a>>16]};FABridge.attachBridge=function(a,c){var b=new FABridge(a,c);FABridge[c]=b;var e=FABridge.initCallbacks[c];if(null!=e){for(var d=0;d<e.length;d++)e[d].call(b);delete FABridge.initCallbacks[c]}};FABridge.blockedMethods={toString:!0,get:!0,set:!0,call:!0};
FABridge.prototype={root:function(){return this.deserialize(this.target.getRoot())},releaseASObjects:function(){return this.target.releaseASObjects()},releaseNamedASObject:function(a){return"object"!=typeof a?!1:this.target.releaseNamedASObject(a.fb_instance_id)},create:function(a){return this.deserialize(this.target.create(a))},makeID:function(a){return(this.bridgeID<<16)+a},getPropertyFromAS:function(a,c){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
FABridge.refCount++;retVal=this.target.getPropFromAS(a,c);retVal=this.handleError(retVal);FABridge.refCount--;return retVal},setPropertyInAS:function(a,c,b){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");FABridge.refCount++;retVal=this.target.setPropInAS(a,c,this.serialize(b));retVal=this.handleError(retVal);FABridge.refCount--;return retVal},callASFunction:function(a,
c){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");FABridge.refCount++;retVal=this.target.invokeASFunction(a,this.serialize(c));retVal=this.handleError(retVal);FABridge.refCount--;return retVal},callASMethod:function(a,c,b){if(0<FABridge.refCount)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
FABridge.refCount++;b=this.encodeJSON(this.serialize(b));retVal=this.target.invokeASMethod(a,c,b);retVal=this.handleError(retVal);FABridge.refCount--;return retVal},invokeLocalFunction:function(a,c){var b,e=this.localFunctionCache[a];void 0!=e&&(b=this.serialize(e.apply(null,this.deserialize(c))));return b},getTypeFromName:function(a){return this.remoteTypeCache[a]},createProxy:function(a,c){var b=this.getTypeFromName(c);instanceFactory.prototype=b;b=new instanceFactory(a);return this.remoteInstanceCache[a]=
b},getProxy:function(a){return this.remoteInstanceCache[a]},addTypeDataToCache:function(a){newType=new ASProxy(this,a.name);for(var c=a.accessors,b=0;b<c.length;b++)this.addPropertyToType(newType,c[b]);a=a.methods;for(b=0;b<a.length;b++)void 0==FABridge.blockedMethods[a[b]]&&this.addMethodToType(newType,a[b]);return this.remoteTypeCache[newType.typeName]=newType},addPropertyToType:function(a,c){var b=c.charAt(0),e;"a"<=b&&"z">=b?(e="get"+b.toUpperCase()+c.substr(1),b="set"+b.toUpperCase()+c.substr(1)):
(e="get"+c,b="set"+c);a[b]=function(a){this.bridge.setPropertyInAS(this.fb_instance_id,c,a)};a[e]=function(){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,c))}},addMethodToType:function(a,c){a[c]=function(){return this.bridge.deserialize(this.bridge.callASMethod(this.fb_instance_id,c,FABridge.argsToArray(arguments)))}},getFunctionProxy:function(a){var c=this;null==this.remoteFunctionCache[a]&&(this.remoteFunctionCache[a]=function(){c.callASFunction(a,FABridge.argsToArray(arguments))});
return this.remoteFunctionCache[a]},getFunctionID:function(a){void 0==a.__bridge_id__&&(a.__bridge_id__=this.makeID(this.nextLocalFuncID++),this.localFunctionCache[a.__bridge_id__]=a);return a.__bridge_id__},serialize:function(a){var c={},b=typeof a;if("number"==b||"string"==b||"boolean"==b||null==b||"undefined"==b)c=a;else if(FABridge.isArray(a)){c=[];for(b=0;b<a.length;b++)c[b]=this.serialize(a[b])}else"function"==b?(c.type=FABridge.TYPE_JSFUNCTION,c.value=this.getFunctionID(a)):FABridge.isASProxy(a)?
(c.type=FABridge.TYPE_ASINSTANCE,c.value=a.fb_instance_id):(c.type=FABridge.TYPE_ANONYMOUS,c.value=a);return c},deserialize:function(a){var c,b=typeof a;if("number"==b||"string"==b||"boolean"==b||null==a||void 0==a)c=this.handleError(a);else if(FABridge.isArray(a)){c=[];for(b=0;b<a.length;b++)c[b]=this.deserialize(a[b])}else if("object"==b){for(b=0;b<a.newTypes.length;b++)this.addTypeDataToCache(a.newTypes[b]);for(var e in a.newRefs)this.createProxy(e,a.newRefs[e]);a.type==FABridge.TYPE_PRIMITIVE?
c=a.value:a.type==FABridge.TYPE_ASFUNCTION?c=this.getFunctionProxy(a.value):a.type==FABridge.TYPE_ASINSTANCE?c=this.getProxy(a.value):a.type==FABridge.TYPE_ANONYMOUS&&(c=a.value)}return c},encodeJSON:function(a){var c,b,e,d="";switch(typeof a){case "object":if(a){if(FABridge.isArray(a)){for(b=0;b<a.length;++b)c=this.encodeJSON(a[b]),d&&(d+=","),d+=c;return"["+d+"]"}if("undefined"!=typeof a.toString){for(b in a)c=a[b],"undefined"!=typeof c&&"function"!=typeof c&&(c=this.encodeJSON(c),d&&(d+=","),d+=
this.encodeJSON(b)+":"+c);return"{"+d+"}"}}return"null";case "number":return isFinite(a)?""+a:"null";case "string":e=a.length;d='"';for(b=0;b<e;b+=1)if(c=a.charAt(b)," "<=c){if("\\"==c||'"'==c)d+="\\";d+=c}else switch(c){case "\b":d+="\\b";break;case "\f":d+="\\f";break;case "\n":d+="\\n";break;case "\r":d+="\\r";break;case "\t":d+="\\t";break;default:c=c.charCodeAt(),d+="\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16)}return d+'"';case "boolean":return""+a;default:return"null"}},addRef:function(a){this.target.incRef(a.fb_instance_id)},
release:function(a){this.target.releaseRef(a.fb_instance_id)},handleError:function(a){if("string"==typeof a&&0==a.indexOf("__FLASHERROR"))throw a=a.split("||"),0<FABridge.refCount&&FABridge.refCount--,Error(a[1]);return a}};ASProxy=function(a,c){this.bridge=a;this.typeName=c;this.className="ASProxy";return this};
ASProxy.prototype={get:function(a){return this.bridge.deserialize(this.bridge.getPropertyFromAS(this.fb_instance_id,a))},set:function(a,c){this.bridge.setPropertyInAS(this.fb_instance_id,a,c)},call:function(a,c){this.bridge.callASMethod(this.fb_instance_id,a,c)},addRef:function(){this.bridge.addRef(this)},release:function(){this.bridge.release(this)}};
var kswfobject=function(){function a(){if(!t){try{var a=f.getElementsByTagName("body")[0].appendChild(f.createElement("span"));a.parentNode.removeChild(a)}catch(c){return}t=!0;for(var a=F.length,b=0;b<a;b++)F[b]()}}function c(a){t?a():F[F.length]=a}function b(a){if(typeof k.addEventListener!=l)k.addEventListener("load",a,!1);else if(typeof f.addEventListener!=l)f.addEventListener("load",a,!1);else if(typeof k.attachEvent!=l)B(k,"onload",a);else if("function"==typeof k.onload){var c=k.onload;k.onload=
function(){c();a()}}else k.onload=a}function e(){var a=f.getElementsByTagName("body")[0],c=f.createElement(y);c.setAttribute("type",G);var b=a.appendChild(c);if(b){var e=0;(function(){if(typeof b.GetVariable!=l){var f=b.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),g.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}else if(10>e){e++;setTimeout(arguments.callee,10);return}a.removeChild(c);b=null;d()})()}else d()}function d(){var a=H.length;if(0<a)for(var c=0;c<a;c++){var b=H[c].id,
d=H[c].callbackFn,e={success:!1,id:b};if(0<g.pv[0]){var f=s(b);f&&(K(H[c].swfVersion)&&!(g.wk&&312>g.wk)?(E(b,!0),d&&(e.success=!0,e.ref=h(b),d(e))):(r(f),d&&d(e)))}else if(E(b,!0),d){if((b=h(b))&&typeof b.SetVariable!=l)e.success=!0,e.ref=b;d(e)}}}function h(a){var b=null;if((a=s(a))&&"OBJECT"==a.nodeName)typeof a.SetVariable!=l?b=a:(a=a.getElementsByTagName(y)[0])&&(b=a);return b}function r(a){if(g.ie&&g.win&&4!=a.readyState){var b=f.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(v(a),
b);a.style.display="none";(function(){4==a.readyState?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(v(a),a)}function v(a){var b=f.createElement("div");if(g.win&&g.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(y)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(1==a[d].nodeType&&"PARAM"==a[d].nodeName)&&8!=a[d].nodeType&&b.appendChild(a[d].cloneNode(!0));return b}function D(a){var b=s(a);b&&"OBJECT"==b.nodeName&&(g.ie&&g.win?(b.style.display=
"none",function(){if(4==b.readyState){var c=s(a);if(c){for(var d in c)"function"==typeof c[d]&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,10)}()):b.parentNode.removeChild(b))}function s(a){var b=null;try{b=f.getElementById(a)}catch(c){}return b}function B(a,b,c){a.attachEvent(b,c);C[C.length]=[a,b,c]}function K(a){var b=g.pv;a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&
b[1]==a[1]&&b[2]>=a[2]?!0:!1}function L(a,b,c,d){if(!g.ie||!g.mac){var e=f.getElementsByTagName("head")[0];if(e){c=c&&"string"==typeof c?c:"screen";d&&(J=q=null);if(!q||J!=c)d=f.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),q=e.appendChild(d),g.ie&&(g.win&&typeof f.styleSheets!=l&&0<f.styleSheets.length)&&(q=f.styleSheets[f.styleSheets.length-1]),J=c;g.ie&&g.win?q&&typeof q.addRule==y&&q.addRule(a,b):q&&typeof f.createTextNode!=l&&q.appendChild(f.createTextNode(a+
" {"+b+"}"))}}}function E(a,b){if(N){var c=b?"visible":"hidden";t&&s(a)?s(a).style.visibility=c:L("#"+a,"visibility:"+c)}}var l="undefined",y="object",G="application/x-shockwave-flash",k=window,f=document,u=navigator,M=!1,F=[function(){M?e():d()}],H=[],I=[],C=[],t=!1,q,J,N=!0,g=function(){var a=typeof f.getElementById!=l&&typeof f.getElementsByTagName!=l&&typeof f.createElement!=l,b=u.userAgent.toLowerCase(),c=u.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),
b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,e=!+"\v1",g=[0,0,0],m=null;if(typeof u.plugins!=l&&typeof u.plugins["Shockwave Flash"]==y){if((m=u.plugins["Shockwave Flash"].description)&&!(typeof u.mimeTypes!=l&&u.mimeTypes[G]&&!u.mimeTypes[G].enabledPlugin))M=!0,e=!1,m=m.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),g[0]=parseInt(m.replace(/^(.*)\..*$/,"$1"),10),g[1]=parseInt(m.replace(/^.*\.(.*)\s.*$/,"$1"),10),g[2]=/[a-zA-Z]/.test(m)?parseInt(m.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0}else if(typeof k.ActiveXObject!=l)try{var h=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(h&&(m=h.GetVariable("$version")))e=!0,m=m.split(" ")[1].split(","),g=[parseInt(m[0],10),parseInt(m[1],10),parseInt(m[2],10)]}catch(s){}return{w3:a,pv:g,wk:b,ie:e,win:d,mac:c}}();(function(){g.w3&&((typeof f.readyState!=l&&"complete"==f.readyState||typeof f.readyState==l&&(f.getElementsByTagName("body")[0]||f.body))&&a(),t||(typeof f.addEventListener!=l&&f.addEventListener("DOMContentLoaded",
a,!1),g.ie&&g.win&&(f.attachEvent("onreadystatechange",function(){"complete"==f.readyState&&(f.detachEvent("onreadystatechange",arguments.callee),a())}),k==top&&function(){if(!t){try{f.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}()),g.wk&&function(){t||(/loaded|complete/.test(f.readyState)?a():setTimeout(arguments.callee,0))}(),b(a)))})();(function(){g.ie&&g.win&&window.attachEvent("onunload",function(){for(var a=C.length,b=0;b<a;b++)C[b][0].detachEvent(C[b][1],
C[b][2]);a=I.length;for(b=0;b<a;b++)D(I[b]);for(var c in g)g[c]=null;g=null;for(var d in kswfobject)kswfobject[d]=null;kswfobject=null})})();return{embedSWF:function(a,b,d,e,h,k,m,q,r,u){var v={success:!1,id:b};g.w3&&!(g.wk&&312>g.wk)&&a&&b&&d&&e&&h?(E(b,!1),c(function(){d+="";e+="";var c={};if(r&&typeof r===y)for(var n in r)c[n]=r[n];c.data=a;c.width=d;c.height=e;n={};if(q&&typeof q===y)for(var k in q)n[k]=q[k];if(m&&typeof m===y)for(var A in m)n.flashvars=typeof n.flashvars!=l?n.flashvars+("&"+
A+"="+m[A]):A+"="+m[A];if(K(h)){var t;k=s(b);if(!(g.wk&&312>g.wk)&&k)if(typeof c.id==l&&(c.id=b),g.ie&&g.win){var w="",p;for(p in c)c[p]!=Object.prototype[p]&&("data"==p.toLowerCase()?n.movie=c[p]:"styleclass"==p.toLowerCase()?w+=' class="'+c[p]+'"':"classid"!=p.toLowerCase()&&(w+=" "+p+'="'+c[p]+'"'));p="";for(var x in n)n[x]!=Object.prototype[x]&&(p+='<param name="'+x+'" value="'+n[x]+'" />');k.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+w+">"+p+"</object>";I[I.length]=
c.id;t=s(c.id)}else{x=f.createElement(y);x.setAttribute("type",G);for(var z in c)c[z]!=Object.prototype[z]&&("styleclass"==z.toLowerCase()?x.setAttribute("class",c[z]):"classid"!=z.toLowerCase()&&x.setAttribute(z,c[z]));for(w in n)n[w]!=Object.prototype[w]&&"movie"!=w.toLowerCase()&&(p=x,z=w,t=n[w],A=f.createElement("param"),A.setAttribute("name",z),A.setAttribute("value",t),p.appendChild(A));k.parentNode.replaceChild(x,k);t=x}n=t;c.id==b&&E(b,!0);v.success=!0;v.ref=n}else E(b,!0);u&&u(v)})):u&&u(v)},
ua:g,removeSWF:function(a){g.w3&&D(a)},createCSS:function(a,b,c,d){g.w3&&L(a,b,c,d)},addDomLoadEvent:c,addLoadEvent:b}}();function KongregateAPI(){this.initialize()}
KongregateAPI.prototype={initialize:function(){this._flashVarsString="";this._flashVarsObject={};this._services={};this._postMessageParams;this._apiLoadedCallback=null;this._paramsReceived=!1;var a=location.search.split("?")[1];if(a)for(var a=a.split("&"),c=0;c<a.length;c++){var b=a[c].split("=");b&&2==b.length&&this.processParam(b[0],b[1])}if(this._postMessageParams=!this.flashVarsObject().kongregate_ansible_path&&top!=window){var e=this;window.addEventListener("message",function(a){e.messageOriginIsKongregate(a)&&
(a=a.data,"params"==a.type&&e.handleParamsMessage(a.data))});top.postMessage("kongregate_request_params","*")}else this._paramsReceived=!0},processParam:function(a,c){0==a.indexOf("kongregate")&&(this._flashVarsObject[a]=c,this._flashVarsString+=a+"="+c+"&")},flashVarsString:function(){return this._flashVarsString},flashVarsObject:function(){return this._flashVarsObject},getVariable:function(a){return this._flashVarsObject[a]},messageOriginIsKongregate:function(a){var c=this._flashVarsObject.kongregate_host;
return c&&a.origin=="http://"+c||a.origin=="https://"+c},loadAPI:function(a){!this._postMessageParams||this.paramsReceived()?this.doLoadAPI(a):this._apiLoadedCallback=a},handleParamsMessage:function(a){if(!this.paramsReceived()){for(var c in a)this.processParam(c,a[c]);this._paramsReceived=!0;this._apiLoadedCallback&&this.doLoadAPI(this._apiLoadedCallback)}},paramsReceived:function(){return this._paramsReceived},doLoadAPI:function(a){var c=this,b=function(){for(var b=FABridge.ansible.root(),d="services stats mtx chat sharedContent analytics".split(" "),
h=0;h<d.length;h++){var r=d[h];c._services[r]=b.getServices(r)}"function"==typeof a&&a()};kswfobject.addDomLoadEvent(function(){c.createAnsible(b)})},getAPI:function(){return this._services},embedFrame:function(a,c){var b=document.getElementById(c?c:"contentdiv"),e;e="<iframe id='content' frameborder='0' style='position:relative;top:0px;left:0px;"+("border:0px none;padding:0px;width:"+b.offsetWidth+"px;height:"+b.offsetHeight+"px;'");e+="src='"+a+"'></iframe>";b.innerHTML=e},createAnsible:function(a){FABridge.addInitializationCallback("ansible",
a);a=document.createElement("div");a.id="ansible_container";a.style.position="absolute";a.style.width=a.style.height="1px";a.style.left=a.style.top="-1000px";document.body.appendChild(a);var c=document.createElement("div");c.id="ansible";a.appendChild(c);a={bridgeName:"ansible",json_encode:"true"};for(var b in this.flashVarsObject())a[b]=this.flashVarsObject()[b];(b=decodeURIComponent(this.getVariable("kongregate_ansible_path")))&&0!=b.indexOf("http://")&&(b="https:"==location.protocol&&0==b.indexOf("chat.kongregate.com")?
"https://"+b.replace("chat.kongregate.com","kongregate1.insnw.net"):"http://"+b);kswfobject.embedSWF(b,"ansible","1","1","9.0.0",null,a,{allowScriptaccess:"always"},null,null)}};kongregateAPI=new KongregateAPI;
